baseURL = 'https://geekbeer.se/'
languageCode = 'sv-se'
title = 'Geek Beer - Ett Tech Meetup'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Events'
pageRef = '/events'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
