baseURL = 'https://geekbeer.se/'
languageCode = 'sv-se'
title = 'Geek Beer - Ett Tech Meetup'

[[menus.main]]
name = 'Meetups'
pageRef = '/meetups'
weight = 20

[[menus.main]]
name = 'Vad är Geek Beer?'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
