name = 'Geek Beer'
license = 'MIT'
licenselink = 'https://github.com/geekbeer/geek-beer-website/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/geekbeer/geek-beer-website'

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['events', 'company']
# features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Name of author', homepage = 'Website of author'},
  {name = 'Name of author', homepage = 'Website of author'}
]

# If the theme has a single author
[author]
  name = 'Jörgen Nilsson'
  homepage = 'https://jorgennilsson.com'
